### ISSUE TITLE
Not Ready for 1.7.10 (deprecated funtions)

### ISSUE THREAD

**Issue by fwolle30** [Cloudhunter/OpenCCSensors#188]
Hi, there are some deprecated functions, that wont work on 1.7.10, I've managed to port this Mod to 1.7.10 by replacing the functions with the suggestions made by MCP (in the deprecated comments).

Tip: Set eclipse so, that it wont compile deprecated function calls, so you can find the parts easily
(Preferences, Java, Compiler, Errors/Warnings, Deprecated and restricted API section.)

I've successfuly testet the code, it work (exept for the issues mentioned in github (currently one))

**Comment by lyqyd** [comment]
Seems to have been resolved fully, I haven't seen any of these issues pop up lately.
