### ISSUE TITLE
Machine sensor doesn't detect MFE or MSFU

### ISSUE THREAD

**Issue by tnjensen** [Cloudhunter/OpenCCSensors#197]
Using openccsensors-1.7.3 with Industrial-Craft-2-Mod-Experimental-1.7.10 [lastest stable build](http://ic2api.player.to:8080/job/IC2_experimental/658/)

If I attach a sensor to the top of a computer and insert a machine sensor card, it fails to detect the MFE sitting right next to it (both in sensorview program and manually printing getTargets())

**Comment by lyqyd** [comment]
MFE and MFSU are both sensed using the Power sensor card, not the Machine sensor card.
